### ISSUE TITLE
Great Randomizer

### ISSUE THREAD

**Issue by InsertMemeHere12192002** [raik199x/Butcher-circus-randomizer#1]
I didn't know if there was another way to leave a comment, but I just wanted to say that I think the randomizer is great and it would be awesome if you did add a trinket randomizer as well. Thank you so much for putting time into making this!

**Comment by raik199x** [comment]
> I didn't know if there was another way to leave a comment, but I just wanted to say that I think the randomizer is great and it would be awesome if you did add a trinket randomizer as well. Thank you so much for putting time into making this!

I'm very happy to hear it! One day i'll add trinket randomization, so stay tuned =)
